AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'vendor/**/*'
    - 'tmp/**/*'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/LineLength:
  Max: 100
  Exclude:
    - 'spec/**/*'
    - 'features/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'features/**/*'
    - '*.gemspec'

Metrics/MethodLength:
  Max: 15

Gemspec/DevelopmentDependencies:
  Enabled: false
