AllCops:
  Include:
    - 'Gemfile'
    - 'Rakefile'
    - 'repokeeper.gemspec'
  Exclude:
    - spec/**/*
    - features/**/*

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Encoding:
  Enabled: false
